config/routes.rb
Rails.application.routes.draw do
	root 'users#index'
  devise_for :users
  resources :users
  resources :photos, only: [:index, :create]
  resources :comments, only: :create
  resources :likes, only: :create
  resources :followers, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

app/models/follower.rb
class Follower < ApplicationRecord
	belongs_to :user
	belongs_to :follower, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_attached_file :image,
                    styles: { medium: '300x300>', thumb: '100x100>'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']
end

app/models/user.rb
class User < ApplicationRecord
	has_many :photos, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :comments, dependent: :destroy

  has_many :followers, :class_name => 'Follower', :foreign_key => 'person_id'
  has_many :following, :class_name => 'Follower', :foreign_key => 'follower_id'
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image,
                    styles: { medium: '300x300>', avatar: '72x72'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    unless user_signed_in?
      redirect_to new_user_session_path
    else
      photo = Photo.find(params[:comment][:photo_id])
      user = User.find(params[:comment][:user_id])

      redirect_to root_path if user != current_user

      user.comments.create(comment_params)
      redirect_to user_path(photo.user)
    end
  end

  private

  def comment_params
  	params.require(:comment).permit(:body, :user_id, :photo_id)
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def create
    unless user_signed_in?
      redirect_to new_user_session_path
    else
      who = User.find(params[:follow][:follower_id])
      whom = User.find(params[:follow][:person_id])
      redirect_to root_path if who != current_user

      if Follower.exists?(follower_id: who.id, person_id: whom.id)
        Follower.find_by(follower_id: who.id, person_id: whom.id).destroy
      else
        Follower.create(follower_id: who.id, person_id: whom.id)
      end
      
      redirect_to :back
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    unless user_signed_in?
      redirect_to new_user_session_path
    else
      photo = Photo.find(params[:like][:photo_id])
      user = User.find(params[:like][:user_id])
      redirect_to root_path if user != current_user

      if Like.exists?(user: user, photo: photo)
        Like.find_by(user: user, photo: photo).destroy
      else
        Like.create(user: user, photo: photo)
      end
      
      redirect_to :back
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to new_user_session_path
    else
      @collection = []
      current_user.following.each do |following|
        user = User.find(following.person_id)
        @collection << user.photos
      end
    end
  end

  def create
  	@user = current_user

  	if @user.photos.create(photo_params)
  		redirect_to @user, notice: 'Photo was successfully created.'
  	else
  		redirect_to @user, notice: 'Smthng wrong.'
  	end
  end

  private

  def photo_params
  	params.require(:photo).permit(:image)	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])  	
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    redirect_to root_path if current_user != @user

    if @user.update(user_params)
      redirect_to user_path(@user) 
    else
      render 'edit'
    end    
  end

  private

  def user_params
  	params.require(:user).permit(:name, :surname, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<h4><%= link_to comment.user.email, user_path(comment.user) %> said: <%= comment.body %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Insta</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<%= link_to root_path do %>
				  <%= image_tag '/logo.png', class: "menu-icon" %>
				<% end %>
			</div>

			<ul class="nav navbar-nav navbar-left">
				<li><%= link_to 'Feed', photos_path %></li>
				<li><%= link_to 'Users', users_path %></li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li><%= link_to 'Profile', user_path(current_user) %></li>
					
				<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Change info", edit_user_path(current_user) %></li>
            <li><%= link_to('Edit registration', edit_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
				<% else %>
					<li><%= link_to('Login', new_user_session_path) %></li>
				<% end %>
				</ul>
		</div>
	</nav>

	<div class="container">
		<%= yield %>
	</div>
	

</body>
</html>

app/views/photos/_photo.html.erb
<div class="thumbnail postOne" >
	<div class="row postTop">
		<div class="col-md-8">
			<%= image_tag photo.user.image.url(:avatar), class: "img-circle", size: "60x60" %>
			<%= link_to photo.user.name + " " + photo.user.surname, user_path(photo.user) %>
		</div>
	</div>		

	<% unless Like.exists?(user_id: current_user, photo_id: photo) %>
		<% button_class = "btn btn-default" %>
		<% glyphicon = "glyphicon glyphicon-heart-empty" %>
	<% else %>
		<% button_class = "btn btn-primary" %>
		<% glyphicon = "glyphicon glyphicon-heart" %>
	<% end %>
	
	<%= image_tag photo.image %>
	<div class="caption">
		<p>
			<%= link_to likes_path(like: {user_id: current_user, photo_id: photo}), method: :post, class: button_class do %>
			Like <i class="<%= glyphicon %>"></i>
			<%= photo.likes.count.to_s %>
			<% end %>

			<button class="btn btn-default smpl" type="button" data-toggle="collapse" data-target="#comment<%= photo.id %>" aria-expanded="false" aria-controls="collapseExample">
				Comment
			</button>
		</p>
	</div>
</div>

<div class="collapse" id="comment<%= photo.id %>">
	<div class="well">
		<%= render photo.comments %>
		<%= "No comments yet" if photo.comments.count == 0 %>
	</div>
	<% if user_signed_in? %>
	<div class="well">
		<%= simple_form_for [photo.comments.build] do |f| %>
			<%= f.input :body %>
			<%= f.hidden_field :user_id, value: current_user.id %>
			<%= f.hidden_field :photo_id, value: photo.id %>
			<%= f.button :submit %>
		<% end %>
	</div>
	<% end %>
</div>

app/views/photos/index.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
	<% @collection.each do |user| %>
	<% user.each do |photo| %>
		<%= render photo %>
	<% end %>
<% end %>
</div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
	<%= f.input :name %>
  <%= f.input :surname %>
  <%= f.input :image, as: :file %>

  <%= f.button :submit %>
<% end %>

app/views/users/_user.html.erb
<% unless Follower.exists?(follower_id: current_user, person_id: user ) %>
<% state_text = "Follow" %>
<% state = "open" %>
<% else %>
<% state_text = "Unfollow" %>
<% state = "close" %>
<% end %>

<tr>
	<td>
		<%= image_tag user.image.url(:avatar) %>
		<%= link_to user.email, user_path(user) %>
	</td>
	<td>
		<% if user == current_user %>
			<h4>It is your profile</h4>
		<% elsif current_user != nil %>
		<%= link_to followers_path(follow: {person_id: user, follower_id: current_user}), method: :post, class: "btn btn-primary" do %>
		<%= state_text %> <i class="glyphicon glyphicon-eye-<%=state%>"></i>
		<% end %>
		<% else %>
		<%= link_to "Follow", new_user_session_path, class: 'btn btn-primary' %>
		<% end %>
	</td>
</tr>

app/views/users/edit.html.erb
<div class="col-md-8 col-md-offset-2">
	<%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<table class="table">
			<tr>
				<th>User</th>
				<th></th>
			</tr>
			<%= render @users %>
		</table>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="twPc-div">
				<a class="twPc-bg twPc-block"></a>

				<div>
					<div class="twPc-button">
						<% if @user == current_user %>
						<%= link_to "Change info", edit_user_path(@user), class: 'btn btn-primary' %>
						
						<button class="btn btn-primary smpl" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
							New photo
						</button>
						<% end %>
						<% unless Follower.exists?(follower_id: current_user, person_id: @user ) %>
							<% state_text = "Follow" %>
							<% state = "open" %>
						<% else %>
							<% state_text = "Unfollow" %>
							<% state = "close" %>
						<% end %>
						<% if @user == current_user %>
						<% elsif current_user != nil %>
						<%= link_to followers_path(follow: {person_id: @user, follower_id: current_user}), method: :post, class: "btn btn-primary" do %>
						<%= state_text %> <i class="glyphicon glyphicon-eye-<%=state%>"></i>
						<% end %>
						<% else %>
						<%= link_to "Follow", new_user_session_path, class: 'btn btn-primary' %>
						<% end %>
					</div>
					
					<%= image_tag @user.image.url(:avatar), class: "twPc-avatarLink" %>					

					<div class="twPc-divUser">
						<div class="twPc-divName">
							<%= link_to @user.name + " " + @user.surname if @user.name != nil && @user.surname != nil %>
						</div>
						<span>
							<%= link_to @user.email %>
						</span>
					</div>

					<div class="twPc-divStats">
						<ul class="twPc-Arrange">
							<li class="twPc-ArrangeSizeFit">
								<a>
									<span class="twPc-StatLabel twPc-block">Posts</span>
									<span class="twPc-StatValue"><%= @user.photos.count %></span>
								</a>
							</li>
							<li class="twPc-ArrangeSizeFit">
								<a>
									<span class="twPc-StatLabel twPc-block">Following</span>
									<span class="twPc-StatValue"><%= @user.following.count %></span>
								</a>
							</li>
							<li class="twPc-ArrangeSizeFit">
								<a>
									<span class="twPc-StatLabel twPc-block">Followers</span>
									<span class="twPc-StatValue"><%= @user.followers.count %></span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>

			<% if user_signed_in? %>
			<div class="collapse" id="collapseExample">
				<div class="well">
					<div class="container">
						<div class="row">
							<div class="col-md-4">
								<%= simple_form_for @user.photos.build do |f| %>
								<div>
									<%= f.file_field :image, required: true %>
								</div>
								<br>
								<div>
									<%= f.button :submit %>
								</div>
								<% end %>
							</div>
						</div>
					</div>   
				</div>
			</div>
			<% end %>

			<div class="feed-photo">
				<% @user.photos.each do |photo| %>
				<%= render photo unless photo.id.nil? %>
				<% end %>
			</div>
		</div>
	</div>
</div>